#!/usr/bin/env python3
"""
AGENT 4: Build interactive command explorer UI
"""
import json
from pathlib import Path
from typing import Dict, Any

def generate_interactive_html(commands_data: Dict[str, Any]) -> str:
    """Generate interactive command explorer web component"""
    html = []
    html.append("<!DOCTYPE html>")
    html.append("<html lang='en'>")
    html.append("<head>")
    html.append("  <meta charset='UTF-8'>")
    html.append("  <meta name='viewport' content='width=device-width, initial-scale=1.0'>")
    html.append("  <title>Claude Automation Core - Command Explorer</title>")
    html.append("  <style>")
    html.append("    * { margin: 0; padding: 0; box-sizing: border-box; }")
    html.append("    body {")
    html.append("      font-family: 'Segoe UI', system-ui, sans-serif;")
    html.append("      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);")
    html.append("      min-height: 100vh;")
    html.append("      padding: 20px;")
    html.append("    }")
    html.append("    .container {")
    html.append("      max-width: 1400px;")
    html.append("      margin: 0 auto;")
    html.append("      background: white;")
    html.append("      border-radius: 20px;")
    html.append("      box-shadow: 0 20px 60px rgba(0,0,0,0.3);")
    html.append("      overflow: hidden;")
    html.append("    }")
    html.append("    .header {")
    html.append("      background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);")
    html.append("      color: white;")
    html.append("      padding: 40px;")
    html.append("      text-align: center;")
    html.append("    }")
    html.append("    .header h1 { font-size: 2.5em; margin-bottom: 10px; }")
    html.append("    .header p { opacity: 0.9; font-size: 1.1em; }")
    html.append("    .stats {")
    html.append("      display: grid;")
    html.append("      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));")
    html.append("      gap: 20px;")
    html.append("      padding: 30px;")
    html.append("      background: #f8fafc;")
    html.append("    }")
    html.append("    .stat-card {")
    html.append("      background: white;")
    html.append("      padding: 20px;")
    html.append("      border-radius: 10px;")
    html.append("      box-shadow: 0 2px 10px rgba(0,0,0,0.1);")
    html.append("      text-align: center;")
    html.append("    }")
    html.append("    .stat-value { font-size: 2em; font-weight: bold; color: #3b82f6; }")
    html.append("    .stat-label { color: #64748b; margin-top: 5px; }")
    html.append("    .controls {")
    html.append("      padding: 30px;")
    html.append("      background: white;")
    html.append("      border-bottom: 2px solid #e2e8f0;")
    html.append("    }")
    html.append("    .search-box {")
    html.append("      width: 100%;")
    html.append("      padding: 15px 20px;")
    html.append("      font-size: 16px;")
    html.append("      border: 2px solid #e2e8f0;")
    html.append("      border-radius: 10px;")
    html.append("      margin-bottom: 20px;")
    html.append("      transition: border-color 0.3s;")
    html.append("    }")
    html.append("    .search-box:focus {")
    html.append("      outline: none;")
    html.append("      border-color: #3b82f6;")
    html.append("    }")
    html.append("    .category-filters {")
    html.append("      display: flex;")
    html.append("      gap: 10px;")
    html.append("      flex-wrap: wrap;")
    html.append("    }")
    html.append("    .category-btn {")
    html.append("      padding: 8px 16px;")
    html.append("      border: 2px solid #e2e8f0;")
    html.append("      background: white;")
    html.append("      border-radius: 20px;")
    html.append("      cursor: pointer;")
    html.append("      transition: all 0.3s;")
    html.append("    }")
    html.append("    .category-btn:hover {")
    html.append("      background: #f1f5f9;")
    html.append("      transform: translateY(-2px);")
    html.append("    }")
    html.append("    .category-btn.active {")
    html.append("      background: #3b82f6;")
    html.append("      color: white;")
    html.append("      border-color: #3b82f6;")
    html.append("    }")
    html.append("    .commands-grid {")
    html.append("      display: grid;")
    html.append("      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));")
    html.append("      gap: 20px;")
    html.append("      padding: 30px;")
    html.append("    }")
    html.append("    .command-card {")
    html.append("      background: white;")
    html.append("      border: 2px solid #e2e8f0;")
    html.append("      border-radius: 10px;")
    html.append("      padding: 20px;")
    html.append("      cursor: pointer;")
    html.append("      transition: all 0.3s;")
    html.append("    }")
    html.append("    .command-card:hover {")
    html.append("      border-color: #3b82f6;")
    html.append("      box-shadow: 0 5px 20px rgba(59, 130, 246, 0.2);")
    html.append("      transform: translateY(-5px);")
    html.append("    }")
    html.append("    .command-name {")
    html.append("      font-size: 1.2em;")
    html.append("      font-weight: bold;")
    html.append("      color: #1e293b;")
    html.append("      margin-bottom: 10px;")
    html.append("      font-family: 'Courier New', monospace;")
    html.append("    }")
    html.append("    .command-purpose {")
    html.append("      color: #64748b;")
    html.append("      font-size: 0.9em;")
    html.append("      line-height: 1.5;")
    html.append("      margin-bottom: 10px;")
    html.append("    }")
    html.append("    .command-tags {")
    html.append("      display: flex;")
    html.append("      gap: 5px;")
    html.append("      flex-wrap: wrap;")
    html.append("    }")
    html.append("    .tag {")
    html.append("      background: #e0e7ff;")
    html.append("      color: #3730a3;")
    html.append("      padding: 4px 10px;")
    html.append("      border-radius: 12px;")
    html.append("      font-size: 0.75em;")
    html.append("    }")
    html.append("    .modal {")
    html.append("      display: none;")
    html.append("      position: fixed;")
    html.append("      top: 0;")
    html.append("      left: 0;")
    html.append("      width: 100%;")
    html.append("      height: 100%;")
    html.append("      background: rgba(0,0,0,0.7);")
    html.append("      z-index: 1000;")
    html.append("      padding: 20px;")
    html.append("      overflow-y: auto;")
    html.append("    }")
    html.append("    .modal-content {")
    html.append("      background: white;")
    html.append("      max-width: 800px;")
    html.append("      margin: 50px auto;")
    html.append("      border-radius: 15px;")
    html.append("      padding: 40px;")
    html.append("    }")
    html.append("    .modal-close {")
    html.append("      float: right;")
    html.append("      font-size: 2em;")
    html.append("      cursor: pointer;")
    html.append("      color: #64748b;")
    html.append("    }")
    html.append("    .modal-close:hover { color: #1e293b; }")
    html.append("    pre {")
    html.append("      background: #1e293b;")
    html.append("      color: #e2e8f0;")
    html.append("      padding: 15px;")
    html.append("      border-radius: 8px;")
    html.append("      overflow-x: auto;")
    html.append("      margin: 10px 0;")
    html.append("    }")
    html.append("  </style>")
    html.append("</head>")
    html.append("<body>")

    # Container
    html.append("  <div class='container'>")

    # Header
    html.append("    <div class='header'>")
    html.append("      <h1>Claude Automation Core</h1>")
    html.append("      <p>Interactive Command Explorer</p>")
    html.append("    </div>")

    # Stats
    stats = commands_data['stats']
    html.append("    <div class='stats'>")
    html.append("      <div class='stat-card'>")
    html.append(f"        <div class='stat-value'>{stats['total_commands']}</div>")
    html.append("        <div class='stat-label'>Total Commands</div>")
    html.append("      </div>")
    html.append("      <div class='stat-card'>")
    html.append(f"        <div class='stat-value'>{stats['total_categories']}</div>")
    html.append("        <div class='stat-label'>Categories</div>")
    html.append("      </div>")
    html.append("      <div class='stat-card'>")
    html.append(f"        <div class='stat-value'>{stats['commands_with_dependencies']}</div>")
    html.append("        <div class='stat-label'>With Dependencies</div>")
    html.append("      </div>")
    html.append("      <div class='stat-card'>")
    html.append(f"        <div class='stat-value'>{stats['commands_with_parameters']}</div>")
    html.append("        <div class='stat-label'>With Parameters</div>")
    html.append("      </div>")
    html.append("    </div>")

    # Controls
    html.append("    <div class='controls'>")
    html.append("      <input type='text' class='search-box' id='searchBox' placeholder='Search commands...'>")
    html.append("      <div class='category-filters' id='categoryFilters'></div>")
    html.append("    </div>")

    # Commands grid
    html.append("    <div class='commands-grid' id='commandsGrid'></div>")

    html.append("  </div>")

    # Modal
    html.append("  <div class='modal' id='commandModal'>")
    html.append("    <div class='modal-content'>")
    html.append("      <span class='modal-close' onclick=\"closeModal()\">&times;</span>")
    html.append("      <div id='modalBody'></div>")
    html.append("    </div>")
    html.append("  </div>")

    # JavaScript
    html.append("  <script>")
    html.append(f"    const COMMANDS_DATA = {json.dumps(commands_data, indent=2)};")
    html.append("    let currentCategory = 'all';")
    html.append("    let searchTerm = '';")
    html.append("")
    html.append("    // Initialize")
    html.append("    function init() {")
    html.append("      renderCategoryFilters();")
    html.append("      renderCommands();")
    html.append("      document.getElementById('searchBox').addEventListener('input', handleSearch);")
    html.append("    }")
    html.append("")
    html.append("    // Render category filters")
    html.append("    function renderCategoryFilters() {")
    html.append("      const container = document.getElementById('categoryFilters');")
    html.append("      const categories = ['all', ...Object.keys(COMMANDS_DATA.taxonomy).sort()];")
    html.append("      container.innerHTML = categories.map(cat => `")
    html.append("        <button class='category-btn ${cat === 'all' ? 'active' : '}'")
    html.append("                onclick='filterByCategory(\"${cat}\")'>${cat}</button>")
    html.append("      `).join('');")
    html.append("    }")
    html.append("")
    html.append("    // Filter by category")
    html.append("    function filterByCategory(category) {")
    html.append("      currentCategory = category;")
    html.append("      document.querySelectorAll('.category-btn').forEach(btn => {")
    html.append("        btn.classList.toggle('active', btn.textContent === category);")
    html.append("      });")
    html.append("      renderCommands();")
    html.append("    }")
    html.append("")
    html.append("    // Handle search")
    html.append("    function handleSearch(e) {")
    html.append("      searchTerm = e.target.value.toLowerCase();")
    html.append("      renderCommands();")
    html.append("    }")
    html.append("")
    html.append("    // Render commands")
    html.append("    function renderCommands() {")
    html.append("      const container = document.getElementById('commandsGrid');")
    html.append("      let commands = COMMANDS_DATA.commands;")
    html.append("")
    html.append("      // Filter by category")
    html.append("      if (currentCategory !== 'all') {")
    html.append("        const categoryCommands = COMMANDS_DATA.taxonomy[currentCategory] || [];")
    html.append("        commands = commands.filter(cmd => categoryCommands.includes(cmd.name));")
    html.append("      }")
    html.append("")
    html.append("      // Filter by search")
    html.append("      if (searchTerm) {")
    html.append("        commands = commands.filter(cmd =>")
    html.append("          cmd.name.toLowerCase().includes(searchTerm) ||")
    html.append("          cmd.purpose.toLowerCase().includes(searchTerm)")
    html.append("        );")
    html.append("      }")
    html.append("")
    html.append("      container.innerHTML = commands.map(cmd => {")
    html.append("        const firstLine = cmd.purpose.split('\\n')[0].replace(/^- /, '').trim();")
    html.append("        return `")
    html.append("          <div class='command-card' onclick='showCommandDetails(${JSON.stringify(cmd.name)})'>")
    html.append("            <div class='command-name'>${cmd.name}</div>")
    html.append("            <div class='command-purpose'>${firstLine}</div>")
    html.append("            <div class='command-tags'>")
    html.append("              ${cmd.categories.map(cat => `<span class='tag'>${cat}</span>`).join('')}")
    html.append("            </div>")
    html.append("          </div>")
    html.append("        `;")
    html.append("      }).join('');")
    html.append("    }")
    html.append("")
    html.append("    // Show command details")
    html.append("    function showCommandDetails(commandName) {")
    html.append("      const cmd = COMMANDS_DATA.commands.find(c => c.name === commandName);")
    html.append("      if (!cmd) return;")
    html.append("")
    html.append("      const modal = document.getElementById('commandModal');")
    html.append("      const body = document.getElementById('modalBody');")
    html.append("")
    html.append("      body.innerHTML = `")
    html.append("        <h2>${cmd.name}</h2>")
    html.append("        <p><strong>Categories:</strong> ${cmd.categories.join(', ')}</p>")
    html.append("        ${cmd.purpose ? `<p>${cmd.purpose}</p>` : ''}")
    html.append("        ${cmd.parameters.length ? `")
    html.append("          <h3>Parameters</h3>")
    html.append("          <ul>")
    html.append("            ${cmd.parameters.map(p => `<li><code>--${p.name}</code> (${p.type})${p.description ? `: ${p.description}` : ''}</li>`).join('')}")
    html.append("          </ul>")
    html.append("        ` : ''}")
    html.append("        ${cmd.dependencies.length ? `<p><strong>Dependencies:</strong> ${cmd.dependencies.join(', ')}</p>` : ''}")
    html.append("        ${cmd.usage ? `<h3>Usage</h3><pre>${cmd.usage}</pre>` : ''}")
    html.append("      `;")
    html.append("")
    html.append("      modal.style.display = 'block';")
    html.append("    }")
    html.append("")
    html.append("    // Close modal")
    html.append("    function closeModal() {")
    html.append("      document.getElementById('commandModal').style.display = 'none';")
    html.append("    }")
    html.append("")
    html.append("    // Close modal on outside click")
    html.append("    window.onclick = function(event) {")
    html.append("      const modal = document.getElementById('commandModal');")
    html.append("      if (event.target === modal) {")
    html.append("        closeModal();")
    html.append("      }")
    html.append("    }")
    html.append("")
    html.append("    // Initialize on load")
    html.append("    window.onload = init;")
    html.append("  </script>")
    html.append("</body>")
    html.append("</html>")

    return '\n'.join(html)

def main():
    print("AGENT 4: Generating interactive UI...")

    # Load parsed commands data from AGENT 1
    data_path = Path(r"C:\Users\Ouroboros\Desktop\portflio-agent1\docs\commands_data.json")

    # Wait for AGENT 1 to complete if needed
    if not data_path.exists():
        print("  [WAIT] Waiting for AGENT 1 to complete...")
        import time
        max_wait = 30
        waited = 0
        while not data_path.exists() and waited < max_wait:
            time.sleep(1)
            waited += 1

        if not data_path.exists():
            print("  [FAIL] AGENT 1 data not available")
            return

    commands_data = json.loads(data_path.read_text(encoding='utf-8'))
    print(f"  [OK] Loaded {len(commands_data['commands'])} commands")

    # Generate interactive HTML
    print("\nGenerating interactive explorer...")
    html_content = generate_interactive_html(commands_data)

    output_dir = Path(r"C:\Users\Ouroboros\Desktop\portflio-agent4\docs")
    output_dir.mkdir(parents=True, exist_ok=True)

    html_path = output_dir / "interactive-explorer.html"
    html_path.write_text(html_content, encoding='utf-8')
    print(f"  [OK] Written to {html_path}")

    print("\n[COMPLETE] AGENT 4")
    print(f"  - Interactive explorer: {html_path}")
    print(f"  - Open in browser to explore {len(commands_data['commands'])} commands")

if __name__ == '__main__':
    main()
