/**
 * Claude Automation Core - Command Type Definitions
 * Total Commands: 79
 * Auto-generated by AGENT 2
 */

/** Command parameter definition */
export interface CommandParameter {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  description?: string;
  required?: boolean;
  default?: any;
}

/** Command execution result */
export interface CommandResult {
  success: boolean;
  output?: string;
  error?: string;
  data?: any;
}

/** Command metadata */
export interface CommandMetadata {
  name: string;
  filename: string;
  purpose: string;
  categories: string[];
  parameters: CommandParameter[];
  dependencies: string[];
}

/** Command categories */
export enum CommandCategory {
  Cognition = 'cognition',
  Evolution = 'evolution',
  Knowledge = 'knowledge',
  Operations = 'operations',
  Orchestration = 'orchestration',
  Security = 'security',
  Templates = 'templates',
  Testing = 'testing',
  Utility = 'utility',
}

/** All available command names */
export type CommandName =
  | '/CHAIN-ALL-COMMANDS' |
  | '/abyssal' |
  | '/adversarial' |
  | '/agent-arena' |
  | '/agent-profiles' |
  | '/analyze-custom-files' |
  | '/attach-security' |
  | '/auto-chain' |
  | '/auto-design' |
  | '/auto-evolve' |
  | '/auto-pipeline' |
  | '/auto-recursive-chain-ai' |
  | '/autorun-all' |
  | '/chaos-evolve' |
  | '/check-drift' |
  | '/config-diff' |
  | '/consciousness-report' |
  | '/contract-adapt' |
  | '/custom-ai' |
  | '/custom-ai-setup' |
  | '/deep-research' |
  | '/deploy-full' |
  | '/destiny' |
  | '/e2e-playwright' |
  | '/e2e-smoke' |
  | '/evolution-status' |
  | '/evolution-summary' |
  | '/experiments-plan' |
  | '/feeling' |
  | '/fix-encoding-errors' |
  | '/fusion' |
  | '/generation' |
  | '/health-probe' |
  | '/hive' |
  | '/hypersense' |
  | '/innovation-scan' |
  | '/intent-map' |
  | '/junk-scan' |
  | '/mega-auto' |
  | '/meshive' |
  | '/multi-ai-orchestrate' |
  | '/multi-websearch' |
  | '/neural-pin' |
  | '/nexus-think' |
  | '/omega' |
  | '/omni-status' |
  | '/pattern-analyze' |
  | '/perf-rag' |
  | '/production-dashboard' |
  | '/project-index' |
  | '/project-overlaps' |
  | '/queue-tasks' |
  | '/rag-build-index' |
  | '/rag-prepare' |
  | '/rag-query' |
  | '/record-movements' |
  | '/recursive-prompt' |
  | '/remote-exec' |
  | '/reverse-reason' |
  | '/sbom' |
  | '/security-review' |
  | '/self-audit' |
  | '/self-evolve' |
  | '/spawn-template' |
  | '/status' |
  | '/suggest-chain' |
  | '/super-chain' |
  | '/swarm' |
  | '/system13' |
  | '/tag' |
  | '/tag-export' |
  | '/tag-query' |
  | '/thought-ecosystem' |
  | '/thought-sense' |
  | '/ultra-critic' |
  | '/ultramind-x13' |
  | '/ultrathink-execute' |
  | '/unified-multi-ai' |
  | '/workflow';

/** Individual command interfaces with specific parameters */

/**
 * /CHAIN-ALL-COMMANDS
 * @category evolution, testing, security, orchestration, knowledge, operations
 * @requires /auto-recursive-chain-ai, /analyze-custom-files, /legacy, /runtime, /evolution-status, /health-probe, /fail, /config-diff, /production-dashboard, /auto-evolve, /self-evolve, /evolution-summary, /autorun-all, /innovation-scan, /multi-ai-orchestrate, /auto-design, /e2e-smoke, /e2e-playwright, /fix-encoding-errors, /junk-scan, /unused, /rag-prepare, /rag-build-index, /rag-query, /perf-rag, /project-index, /project-overlaps, /duplicate, /intent-map, /deploy-full, /attach-security, /sbom, /auto-pipeline, /experiments-plan, /system13, /agent-profiles
 */
export interface ChainAllCommandsCommand {
  command: '/CHAIN-ALL-COMMANDS';
  parameters?: {
    Combine?: string;
    Recursive?: string;
    recursive?: string;
    MaxIterations?: string;
    FitnessThreshold?: string;
    Background?: string;
    recursive-chain-ai?: string;
    -?: string;
    custom-files?: string;
    status?: string;
    probe?: string;
    diff?: string;
    dashboard?: string;
    /** `/auto-recursive-chain-ai` - **Auto-recursive AI that chains ALL commands** (NEW!) */
    Improvement?: string;
    evolve?: string;
    evolution?: string;
    evolve?: string;
    summary?: string;
    all?: string;
    /** `/innovation-scan` - Generate innovation report with experiment suggestions */
    evolution?: string;
    /** `/multi-ai-orchestrate` - Coordinate evolution across Claude, Codex, and GPT-4 */
    AI?: string;
    design?: string;
    smoke?: string;
    to-end?: string;
    playwright?: string;
    to-end?: string;
    encoding-errors?: string;
    healer?: string;
    run?: string;
    scan?: string;
    prepare?: string;
    build-index?: string;
    IDF?: string;
    query?: string;
    rag?: string;
    index?: string;
    level?: string;
    overlaps?: string;
    map?: string;
    full?: string;
    security?: string;
    pipeline?: string;
    plan?: string;
    profiles?: string;
    -?: string;
    custom-files?: string;
    status?: string;
    probe?: string;
    MinFitness?: string;
    diff?: string;
    dashboard?: string;
    custom-files?: string;
    status?: string;
    encoding-errors?: string;
    dry-run?: string;
    encoding-errors?: string;
    no-dry-run?: string;
    to-end?: string;
    smoke?: string;
    evolve?: string;
    summary?: string;
    status?: string;
    AI?: string;
    custom-files?: string;
    status?: string;
    design?: string;
    AI?: string;
    ai-orchestrate?: string;
    scan?: string;
    all?: string;
    ApplySafeActions?: string;
    all?: string;
    IntervalSeconds?: string;
    ApplySafeActions?: string;
    all?: string;
    MaxCycles?: string;
    ApplySafeActions?: string;
    prepare?: string;
    build-index?: string;
    query?: string;
    rag?: string;
    index?: string;
    overlaps?: string;
    map?: string;
    Deployment?: string;
    probe?: string;
    MinFitness?: string;
    to-end?: string;
    smoke?: string;
    playwright?: string;
    diff?: string;
    dashboard?: string;
    Evolution?: string;
    evolve?: string;
    AI?: string;
    Recursive?: string;
    recursive-chain-ai?: string;
    -?: string;
    status?: string;
    custom-files?: string;
    evolve?: string;
    smoke?: string;
    /** Run `/evolution-status` to see current fitness */
    to-end?: string;
    ai-orchestrate?: string;
    custom-files?: string;
    status?: string;
    query?: string;
    prepare?: string;
    build-index?: string;
    all?: string;
    -?: string;
    custom-files?: string;
    output-format?: string;
    status?: string;
    output-format?: string;
    probe?: string;
    OutputFormat?: string;
    dashboard?: string;
    output-format?: string;
    scan?: string;
    -?: string;
    probe?: string;
    encoding-errors?: string;
    smoke?: string;
    status?: string;
    custom-files?: string;
    evolve?: string;
    summary?: string;
    index?: string;
    design?: string;
    ai-orchestrate?: string;
    all?: string;
    evolve?: string;
    summary?: string;
    design?: string;
    -?: string;
    custom-files?: string;
    probe?: string;
    encoding-errors?: string;
    evolve?: string;
    smoke?: string;
    status?: string;
    evolve?: string;
    ai-orchestrate?: string;
    -?: string;
    probe?: string;
    smoke?: string;
    status?: string;
    scan?: string;
    design?: string;
    custom-files?: string;
    diff?: string;
    probe?: string;
    dashboard?: string;
    status?: string;
    evolve?: string;
    summary?: string;
    AI?: string;
    custom-files?: string;
    status?: string;
    design?: string;
    ai-orchestrate?: string;
    -?: string;
    run?: string;
    encoding-errors?: string;
    safe?: string;
    -?: string;
  };
}

/**
 * /abyssal
 * @category testing, security, orchestration, templates
 * @example
 * Invoke with ABYSSAL syntax:
 * ```
 * ABYSSAL[ROADMAP]("Rust Code Hive v2")
 */
export interface AbyssalCommand {
  command: '/abyssal';
  parameters?: {
    auto?: string;
    expand?: string;
    chain?: string;
  };
}

/**
 * /adversarial
 * @category testing
 * @example
 * ```
 * /adversarial [action] [tools]
 * ```
 */
export interface AdversarialCommand {
  command: '/adversarial';
  parameters?: {
    Test?: string;
    testing?: string;
  };
}

/**
 * /agent-arena
 * @category testing, orchestration, knowledge, cognition
 * @example
 * ```bash
 */
export interface AgentArenaCommand {
  command: '/agent-arena';
  parameters?: {
    arena?: string;
    agent?: string;
    check?: string;
    list?: string;
    quick?: string;
    run?: string;
    full?: string;
    run?: string;
    agents?: string;
    run?: string;
    categories?: string;
    to-head?: string;
    h2h?: string;
    --------?: string;
    ----?: string;
    -----?: string;
    worked?: string;
    each?: string;
    --------?: string;
    -----?: string;
    --------------------------------------------------------------------?: string;
    to-Head?: string;
    arena?: string;
    quick?: string;
    arena?: string;
    h2h?: string;
    arena?: string;
    run?: string;
    categories?: string;
    arena?: string;
    full?: string;
    categories?: string;
  };
}

/**
 * /agent-profiles
 * Show the current profiles for Claude, Codex, and GPT-4 in a machine-readable format.
 * @category orchestration
 * @example
 * - `python D:\claude\tools\agent_profiles.py`
 * Output:
 */
export interface AgentProfilesCommand {
  command: '/agent-profiles';
  parameters?: {
    profiles?: string;
    4?: string;
    readable?: string;
    agent?: string;
  };
}

/**
 * /analyze-custom-files
 * Analyze Claude-related configuration across:
 * @category evolution, orchestration
 * @requires /evolution-status, /multi-ai-orchestrate
 */
export interface AnalyzeCustomFilesCommand {
  command: '/analyze-custom-files';
  parameters?: {
    custom-files?: string;
    related?: string;
    healing?: string;
    command?: string;
    custom-files?: string;
    output-format?: string;
    status?: string;
    ai-orchestrate?: string;
    safe?: string;
  };
}

/**
 * /attach-security
 * Dynamically attach the "Security Red Teamer" persona to the current session.
 * @category testing, security
 * @example
 * - `python D:\claude\hooks\attach_security_agent.py`
 * Output:
 */
export interface AttachSecurityCommand {
  command: '/attach-security';
  parameters?: {
    security?: string;
    sentinel-nexus?: string;
    METHOD?: string;
    red-teamer?: string;
  };
}

/**
 * /auto-chain
 * @category evolution, testing, orchestration, knowledge
 * @example
 * ```
 * /auto-chain [intent] [--iterations N] [--threshold SCORE]
 * ```
 */
export interface AutoChainCommand {
  command: '/auto-chain';
  parameters?: {
    Recursive?: string;
    improvement?: string;
    chain?: string;
    iterations?: string;
    threshold?: string;
    iterations?: string;
    threshold?: string;
    dry-run?: string;
    status?: string;
    -------------?: string;
    -----------------?: string;
    custom-files?: string;
    status?: string;
    encoding-errors?: string;
    smoke?: string;
    diff?: string;
    0?: string;
    evolve?: string;
    summary?: string;
    design?: string;
    scan?: string;
    ai-orchestrate?: string;
    improvement?: string;
    chain?: string;
    chain?: string;
    chain?: string;
    status?: string;
  };
}

/**
 * /auto-design
 * Run the auto design analyzer to gather a comprehensive snapshot of system state and suggested design changes.
 * @category evolution, testing
 * @example
 * - `python D:\scripts\auto_design_analyzer.py`
 * Output:
 */
export interface AutoDesignCommand {
  command: '/auto-design';
  parameters?: {
    design?: string;
    evolution?: string;
    action?: string;
    level?: string;
    signal?: string;
    4?: string;
  };
}

/**
 * /auto-evolve
 * Run an automated self-evolution generation using your contract and evolution bundle.
 * @category evolution, testing, knowledge
 * @requires /e2e-smoke, /evolution-status, /evolution-summary
 */
export interface AutoEvolveCommand {
  command: '/auto-evolve';
  parameters?: {
    evolve?: string;
    evolution?: string;
    apply-safe-actions?: string;
    approved?: string;
    healer?: string;
    4?: string;
    smoke?: string;
    to-end?: string;
    status?: string;
    evolve?: string;
    summary?: string;
  };
}

/**
 * /auto-pipeline
 * Run a full improvement loop in one command:
 * @category evolution, orchestration
 * @example
 * - `python D:\claude\tools\command_usage_logger.py --command /auto-pipeline`
 * - `python D:\claude\tools\auto_pipeline.py`
 */
export interface AutoPipelineCommand {
  command: '/auto-pipeline';
  parameters?: {
    pipeline?: string;
    evolution?: string;
    AI?: string;
    command?: string;
    pipeline?: string;
    shot?: string;
  };
}

/**
 * /auto-recursive-chain-ai
 * Auto-recursive, looping, chaining AI orchestrator that automatically chains all slash commands in recursive loops with intelligent decision-making.
 * @category evolution, testing, orchestration, operations
 * @requires /analyze-custom-files, /evolution-status
 * @example
 * ```bash
 */
export interface AutoRecursiveChainAiCommand {
  command: '/auto-recursive-chain-ai';
  parameters?: {
    recursive-chain-ai?: string;
    recursive?: string;
    making?: string;
    max-iterations?: string;
    fitness-threshold?: string;
    cycles-only?: string;
    max-iterations?: string;
    making?: string;
    Improvement?: string;
    custom-files?: string;
    status?: string;
    encoding-errors?: string;
    smoke?: string;
    diff?: string;
    evolve?: string;
    summary?: string;
    design?: string;
    scan?: string;
    ai-orchestrate?: string;
    diff?: string;
    probe?: string;
    cycles?: string;
    time?: string;
    custom-files?: string;
    status?: string;
    /** Command usage logger */
    evolution?: string;
    recursive?: string;
    max-iterations?: string;
    fitness-threshold?: string;
    cycles-only?: string;
    max-iterations?: string;
    recursively?: string;
  };
}

/**
 * /autorun-all
 * Continuously run the full auto-evolution loop (generation + summary + design analysis) according to the self-evolution contract.
 * @category evolution, testing, knowledge
 * @example
 * - `D:\scripts\autorun_all.ps1 -ApplySafeActions`
 * Behavior:
 */
export interface AutorunAllCommand {
  command: '/autorun-all';
  parameters?: {
    all?: string;
    evolution?: string;
    evolution?: string;
    ApplySafeActions?: string;
    apply-safe-actions?: string;
    IntervalSeconds?: string;
    MaxCycles?: string;
    ApplySafeActions?: string;
    approved?: string;
  };
}

/**
 * /chaos-evolve
 * @category evolution, knowledge, templates, cognition
 * @requires /13, /oscillates, /stabilizes
 * @example
 * ```
 * /chaos-evolve <query> [--iterations N] [--depth D] [--seed S]
 * ```
 */
export interface ChaosEvolveCommand {
  command: '/chaos-evolve';
  parameters?: {
    evolve?: string;
    iterations?: string;
    depth?: string;
    seed?: string;
    iterations?: string;
    depth?: string;
    seed?: string;
    json?: string;
    deterministic?: string;
    degree?: string;
    evolutions?: string;
    evolve?: string;
    evolve?: string;
    iterations?: string;
    depth?: string;
    evolve?: string;
    seed?: string;
  };
}

/**
 * /check-drift
 * ** Early detection of configuration inconsistencies before they cause production issues
 * @category evolution, orchestration, operations
 * @requires /automation_core, /claude, /tools, /config_diff, /removed, /modified, /medium, /high, /self-evolve, /scripts, /sync_claude, /command
 * @example
 * ** Type `/check-drift` to run drift detection
 */
export interface CheckDriftCommand {
  command: '/check-drift';
  parameters?: {
    /** Configuration Drift Monitoring */
    drift?: string;
    of-truth?: string;
    -?: string;
    -?: string;
    detailed?: string;
    -?: string;
    -?: string;
    evolve?: string;
    evolve?: string;
    AI?: string;
    -?: string;
    drift?: string;
    -?: string;
    only?: string;
    2?: string;
    10?: string;
    -?: string;
    ----------?: string;
    ------?: string;
    -?: string;
    drift?: string;
  };
}

/**
 * /config-diff
 * **
 * @category evolution, operations
 * @example
 * **
 * ```bash
 * python D:\claude\tools\command_usage_logger.py --command /config-diff
 */
export interface ConfigDiffCommand {
  command: '/config-diff';
  parameters?: {
    diff?: string;
    command?: string;
    diff?: string;
  };
}

/**
 * /consciousness-report
 * Generate insights from Omni Cortex Tier 3 (Consciousness Layer)
 * @category operations, cognition
 * @example
 * ```bash
 * python D:\claude\tools\consciousness_report.py
 * ```
 */
export interface ConsciousnessReportCommand {
  command: '/consciousness-report';
  parameters?: {
    report?: string;
    confidence?: string;
  };
}

/**
 * /contract-adapt
 * Inspect and optionally adapt the self-evolution contract based on recent generations.
 * @category evolution, cognition
 */
export interface ContractAdaptCommand {
  command: '/contract-adapt';
  parameters?: {
    adapt?: string;
    evolution?: string;
    window?: string;
    window?: string;
    apply?: string;
    action?: string;
    apply?: string;
  };
}

/**
 * /custom-ai
 * @category orchestration, knowledge, operations
 * @example
 * ```
 * /custom-ai <query> [--endpoint ENDPOINT] [--discover]
 * ```
 */
export interface CustomAiCommand {
  command: '/custom-ai';
  parameters?: {
    endpoint?: string;
    healing?: string;
    ai?: string;
    endpoint?: string;
    discover?: string;
    endpoint?: string;
    discover?: string;
    status?: string;
    route?: string;
    discovers?: string;
    compatible?: string;
    time?: string;
    Healing?: string;
    recovery?: string;
    routing?: string;
    ai?: string;
    ai?: string;
    discover?: string;
    ai?: string;
    status?: string;
    ai?: string;
    endpoint?: string;
  };
}

/**
 * /custom-ai-setup
 * @category security, orchestration, knowledge, operations
 * @requires /SSE, /HTTP, /api, /chat, /TLS, /v1, /localhost
 * @example
 * ```bash
 * /custom-ai-setup [command] [options]
 * ```
 */
export interface CustomAiSetupCommand {
  command: '/custom-ai-setup';
  parameters?: {
    ai-setup?: string;
    ai-setup?: string;
    query?: string;
    capability?: string;
    status?: string;
    time?: string;
    stream?: string;
    prompt?: string;
    type?: string;
    Learning?: string;
    record?: string;
    analyze?: string;
    healing?: string;
    heal?: string;
    report?: string;
    train-routing?: string;
    save?: string;
    train-anomaly?: string;
    load?: string;
    predict?: string;
    sniff?: string;
    count?: string;
    interface?: string;
    merge?: string;
    query?: string;
    capability?: string;
    status?: string;
    discover?: string;
    train?: string;
    heal?: string;
    heal?: string;
    recommend?: string;
    report?: string;
    save?: string;
    Endpoint?: string;
    Learning?: string;
    learn?: string;
    Healing?: string;
    discover?: string;
    based?: string;
    based?: string;
    4?: string;
    3?: string;
    based?: string;
    time?: string;
    query?: string;
    capability?: string;
    query?: string;
    capability?: string;
    query?: string;
    capability?: string;
    stream?: string;
    prompt?: string;
    optimize?: string;
    train?: string;
    heal?: string;
  };
}

/**
 * /deep-research
 * @category evolution, security, orchestration, knowledge, cognition
 * @requires /How, /Present, /Future, /localhost, /api, /ultrathink, /think, /GPT-4
 * @example
 * ```bash
 * /deep-research [query] [--algo ALGORITHM] [--depth LEVEL] [--nexus] [--save]
 * ```
 */
export interface DeepResearchCommand {
  command: '/deep-research';
  parameters?: {
    research?: string;
    research?: string;
    algo?: string;
    depth?: string;
    nexus?: string;
    save?: string;
    ----?: string;
    ---------?: string;
    -----------?: string;
    of-Thought?: string;
    of-Verification?: string;
    correcting?: string;
    Perspective?: string;
    aware?: string;
    domain?: string;
    -----?: string;
    --------?: string;
    ------?: string;
    ---------?: string;
    algo?: string;
    depth?: string;
    algo?: string;
    depth?: string;
    nexus?: string;
    depth?: string;
    algo?: string;
    depth?: string;
    research?: string;
    algo?: string;
    depth?: string;
    research?: string;
    algo?: string;
    depth?: string;
    research?: string;
    algo?: string;
    depth?: string;
    research?: string;
    algo?: string;
    depth?: string;
    research?: string;
    algo?: string;
    depth?: string;
    Recursive?: string;
    selected?: string;
    AI?: string;
    4?: string;
    AI?: string;
  };
}

/**
 * /deploy-full
 * Run a full-stack deploy pipeline including health checks, RAG smoke tests, and artifact staging.
 * @category testing, knowledge, operations
 * @example
 * - `D:\scripts\full_stack_deploy.ps1`
 * Behavior:
 */
export interface DeployFullCommand {
  command: '/deploy-full';
  parameters?: {
    full?: string;
    stack?: string;
    SkipBuild?: string;
    SkipTests?: string;
  };
}

/**
 * /destiny
 * @category security, orchestration, knowledge, cognition
 * @example
 * ```
 * /destiny <query> [--master] [--branch BRANCH] [--keywords] [--interactive]
 * ```
 */
export interface DestinyCommand {
  command: '/destiny';
  parameters?: {
    master?: string;
    branch?: string;
    keywords?: string;
    interactive?: string;
    master?: string;
    branch?: string;
    keywords?: string;
    interactive?: string;
    json?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    master?: string;
    branch?: string;
    interactive?: string;
    keywords?: string;
    master?: string;
  };
}

/**
 * /e2e-playwright
 * Run the advanced Playwright E2E + visual testing suite.
 * @category evolution, testing, orchestration
 * @requires /visual
 * @example
 * - `D:\scripts\run_playwright_e2e.ps1`
 * Behavior:
 */
export interface E2EPlaywrightCommand {
  command: '/e2e-playwright';
  parameters?: {
    playwright?: string;
    visual-e2e-testing?: string;
    visual-e2e-testing?: string;
    evolution?: string;
    evolution?: string;
    Profile?: string;
    evolution?: string;
    playwright?: string;
    hoc?: string;
  };
}

/**
 * /e2e-smoke
 * Run a fast end-to-end smoke test across core tools (analysis, healing, junk scan, RAG).
 * @category evolution, testing, orchestration, knowledge, operations
 * @requires /evolution-status, /auto-evolve
 * @example
 * - `python D:\scripts\run_e2e_smoke.py`
 * Checks:
 */
export interface E2ESmokeCommand {
  command: '/e2e-smoke';
  parameters?: {
    smoke?: string;
    to-end?: string;
    healer?: string;
    run?: string;
    smoke?: string;
    to-end?: string;
    status?: string;
    evolve?: string;
  };
}

/**
 * /evolution-status
 * Report the current health and evolution status of the Claude + Codex system.
 * @category evolution, testing, orchestration, operations
 * @requires /analyze-custom-files, /fix-encoding-errors, /e2e-smoke, /auto-evolve
 * @example
 * - First log usage:
 * - `python D:\claude\tools\command_usage_logger.py --command /evolution-status`
 * - Then run:
 */
export interface EvolutionStatusCommand {
  command: '/evolution-status';
  parameters?: {
    status?: string;
    command?: string;
    status?: string;
    output-format?: string;
    custom-files?: string;
    healer?: string;
    encoding-errors?: string;
    status?: string;
    smoke?: string;
    evolve?: string;
  };
}

/**
 * /evolution-summary
 * Show a concise summary of the most recent auto-evolution generation.
 * @category evolution, knowledge
 * @example
 * - `python D:\scripts\summarize_generation.py`
 * Output:
 */
export interface EvolutionSummaryCommand {
  command: '/evolution-summary';
  parameters?: {
    summary?: string;
    evolution?: string;
  };
}

/**
 * /experiments-plan
 * Show a simple, categorized experiments plan based on the latest innovation ideas.
 * @category testing
 * @example
 * - `python D:\claude\tools\experiments_plan.py`
 * Output:
 */
export interface ExperimentsPlanCommand {
  command: '/experiments-plan';
  parameters?: {
    plan?: string;
    4?: string;
  };
}

/**
 * /feeling
 * @category orchestration, templates
 * @example
 * ```
 * /feeling <thought> [--analyze] [--destiny] [--visualize]
 * ```
 */
export interface FeelingCommand {
  command: '/feeling';
  parameters?: {
    chained?: string;
    analyze?: string;
    destiny?: string;
    visualize?: string;
    analyze?: string;
    destiny?: string;
    weighted?: string;
    visualize?: string;
    json?: string;
    ---------?: string;
    ----?: string;
    ------?: string;
    ---?: string;
    /** **Discovery**: doubt -> wonder -> intuition -> analysis -> wisdom */
    Chains?: string;
    CM-CH-CM-DH-EM-NM-RH?: string;
    analyze?: string;
    destiny?: string;
    visualize?: string;
    destiny?: string;
  };
}

/**
 * /fix-encoding-errors
 * Run the encoding self-healer against the runtime Claude directory to reduce or eliminate encoding-related errors.
 * @category utility
 */
export interface FixEncodingErrorsCommand {
  command: '/fix-encoding-errors';
  parameters?: {
    encoding-errors?: string;
    healer?: string;
    related?: string;
    dry-run?: string;
    no-dry-run?: string;
    command?: string;
    encoding-errors?: string;
    dry?: string;
  };
}

/**
 * /fusion
 * @category orchestration, knowledge, cognition
 * @requires /conflict, /synthesis, /cascade, /adversarial
 * @example
 * ```
 * /fusion "query" [options]
 * ```
 */
export interface FusionCommand {
  command: '/fusion';
  parameters?: {
    strategy?: string;
    tools?: string;
    separated?: string;
    /** **cascade** - Feed output of one into next */
    order?: string;
    strategy?: string;
    strategy?: string;
    tools?: string;
    strategy?: string;
  };
}

/**
 * /generation
 * @category evolution, orchestration, knowledge
 * @requires /evolution-status
 * @example
 * ```
 * /generation current
 * /generation bump <level>
 */
export interface GenerationCommand {
  command: '/generation';
  parameters?: {
    specific?: string;
    main?: string;
    message?: string;
    message?: string;
    message?: string;
    message?: string;
    m?: string;
    fitness?: string;
    validate?: string;
    dry-run?: string;
    limit?: string;
    source?: string;
    limit?: string;
    source?: string;
    json?: string;
    Bumping?: string;
    Healing?: string;
    Aware?: string;
    feature-name?: string;
    bumping?: string;
    bump?: string;
    message?: string;
    fitness?: string;
    validate?: string;
    limit?: string;
    status?: string;
    evolve?: string;
    bumps?: string;
    healing?: string;
    bumps?: string;
  };
}

/**
 * /health-probe
 * Run a health snapshot of the Claude + Nexus stack and get a simple pass/fail based on fitness.
 * @category evolution, operations
 * @requires /fail
 * @example
 * - `D:\scripts\health_probe.ps1 -MinFitness 0.6 -OutputFormat json`
 * Notes:
 */
export interface HealthProbeCommand {
  command: '/health-probe';
  parameters?: {
    probe?: string;
    MinFitness?: string;
    OutputFormat?: string;
    safety?: string;
  };
}

/**
 * /hive
 * @category evolution, testing, security, knowledge, operations
 */
export interface HiveCommand {
  command: '/hive';
  parameters?: {
    compaction?: string;
    -?: string;
    action?: string;
    keywords?: string;
    age-threshold?: string;
    -?: string;
    Critique?: string;
    -?: string;
    Maintenance?: string;
    -?: string;
    -?: string;
    20?: string;
    compact?: string;
    -?: string;
    -?: string;
    Refresh?: string;
  };
}

/**
 * /hypersense
 * @category security, orchestration, knowledge
 * @requires /tension
 * @example
 * ```
 * /hypersense [action] [options]
 * ```
 */
export interface HypersenseCommand {
  command: '/hypersense';
  parameters?: {
    channel?: string;
    tool?: string;
    t?: string;
    channel?: string;
    c?: string;
    message?: string;
    m?: string;
    state?: string;
    s?: string;
    json?: string;
    -------?: string;
    -------?: string;
    tool?: string;
    tool?: string;
    state?: string;
    tool?: string;
    channel?: string;
    message?: string;
    channel?: string;
    tool?: string;
    state?: string;
    tool?: string;
    channel?: string;
    message?: string;
    channel?: string;
  };
}

/**
 * /innovation-scan
 * Generate an innovation report with suggested experiments and upgrades.
 * @category evolution
 * @example
 * - `python D:\claude\tools\command_usage_logger.py --command /innovation-scan`
 * - `python D:\claude\tools\innovation_scan.py`
 */
export interface InnovationScanCommand {
  command: '/innovation-scan';
  parameters?: {
    scan?: string;
    command?: string;
    scan?: string;
  };
}

/**
 * /intent-map
 * Summarize recent Claude chat history into thematic buckets (projects/tools, research, bugs, TODOs, etc.).
 * @category knowledge
 * @requires /tools
 * @example
 * - `python D:\scripts\analyze_history_logs.py --output-format text`
 * Output:
 */
export interface IntentMapCommand {
  command: '/intent-map';
  parameters?: {
    map?: string;
    output-format?: string;
  };
}

/**
 * /junk-scan
 * Recursively scan `D:\` and heuristically identify candidate junk files and folders (temporary, build artefacts, large logs).
 * @category utility
 * @example
 * - `python D:\claude\tools\junk_scan.py --output-format text`
 * Notes:
 */
export interface JunkScanCommand {
  command: '/junk-scan';
  parameters?: {
    scan?: string;
    output-format?: string;
  };
}

/**
 * /mega-auto
 * @category evolution, orchestration, templates
 * @requires /consensus
 * @example
 * :
 * Just use ABYSSAL[*] syntax anywhere in your prompt. The system will automatically:
 */
export interface MegaAutoCommand {
  command: '/mega-auto';
  parameters?: {
    expand?: string;
    spawn?: string;
    fork?: string;
    chain?: string;
    synthesize?: string;
    execution?: string;
  };
}

/**
 * /meshive
 * @category evolution, testing, security, orchestration, knowledge, cognition
 * @requires /micronode
 * @example
 * ```
 * /meshive <intent> [--topology] [--visualize] [--batch INTENTS]
 * ```
 */
export interface MeshiveCommand {
  command: '/meshive';
  parameters?: {
    Topic?: string;
    Nested?: string;
    Layer?: string;
    topology?: string;
    visualize?: string;
    batch?: string;
    topology?: string;
    visualize?: string;
    batch?: string;
    /** `--json`: Output JSON format */
    separated?: string;
    based?: string;
    LAYERS?: string;
    Cutting?: string;
    macro?: string;
    level?: string;
    micro?: string;
    /** cross-macro: Elite mesh connections */
    cluster?: string;
    LAYERS?: string;
    topology?: string;
    visualize?: string;
    batch?: string;
  };
}

/**
 * /multi-ai-orchestrate
 * Coordinate an evolution cycle across Claude, Codex, and GPT-4.
 * @category evolution, orchestration, templates
 * @example
 * - First log usage:
 * - `python D:\claude\tools\command_usage_logger.py --command /multi-ai-orchestrate`
 * - Then run:
 */
export interface MultiAiOrchestrateCommand {
  command: '/multi-ai-orchestrate';
  parameters?: {
    ai-orchestrate?: string;
    4?: string;
    command?: string;
    ai-orchestrate?: string;
    output-json?: string;
    4?: string;
    level?: string;
  };
}

/**
 * /multi-websearch
 * Use Claude in multiple parallel sessions (or tabs) to perform wide, deep web research on a topic and then merge the findings into a single synthesis.
 * @category security, orchestration, knowledge, operations, templates
 * @requires /cons
 */
export interface MultiWebsearchCommand {
  command: '/multi-websearch';
  parameters?: {
    websearch?: string;
    /** Topic: `$TOPIC` */
    -------------------------------------?: string;
    level?: string;
    -------------------?: string;
    session?: string;
  };
}

/**
 * /neural-pin
 * @category knowledge
 * @example
 * ```
 * /neural-pin <action> [options]
 * ```
 */
export interface NeuralPinCommand {
  command: '/neural-pin';
  parameters?: {
    decide?: string;
    pin?: string;
    ------?: string;
    -----------?: string;
    decide?: string;
    name?: string;
    thought?: string;
    pin-id?: string;
    trigger?: string;
    options?: string;
    separated?: string;
    visualize?: string;
    levels?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    DECIDE?: string;
    -?: string;
    -?: string;
    -?: string;
    pin?: string;
    name?: string;
    thought?: string;
    pin?: string;
    pin-id?: string;
    pin?: string;
    thought?: string;
    trigger?: string;
    decide?: string;
    pin?: string;
    options?: string;
    pin?: string;
    pin?: string;
    pin?: string;
  };
}

/**
 * /nexus-think
 * @category knowledge, operations, templates, cognition
 * @requires /15, /nexus-status, /localhost, /api, /ultrathink, /think, /json, /nexus-health
 * @example
 * ```
 * /nexus-think <query> [--depth DEPTH]
 * ```
 */
export interface NexusThinkCommand {
  command: '/nexus-think';
  parameters?: {
    of-thought?: string;
    think?: string;
    depth?: string;
    depth?: string;
    nexus?: string;
    of-thought?: string;
    think?: string;
    status?: string;
    X?: string;
    H?: string;
    Type?: string;
    d?: string;
    status?: string;
    health?: string;
  };
}

/**
 * /omega
 * @category cognition
 * @example
 * ```
 * /omega [action] [value]
 * ```
 */
export interface OmegaCommand {
  command: '/omega';
  parameters?: {
    /** `omega` - Direct omega transmission */
    thought?: string;
    /** SELF-GENERATING */
    THOUGHT?: string;
    GENERATING?: string;
  };
}

/**
 * /omni-status
 * Check Omni Cortex integration status
 * @category operations, cognition
 * @requires /disabled
 * @example
 * ```bash
 * python D:\claude\tools\omni_status.py
 * ```
 */
export interface OmniStatusCommand {
  command: '/omni-status';
  parameters?: {
    status?: string;
  };
}

/**
 * /pattern-analyze
 * @category testing, knowledge, cognition
 * @requires /failure, /anomaly, /slow, /5
 * @example
 * ```
 * /pattern-analyze [--quick] [--json] [--profile AGENT] [--patterns]
 * ```
 */
export interface PatternAnalyzeCommand {
  command: '/pattern-analyze';
  parameters?: {
    analyze?: string;
    quick?: string;
    json?: string;
    profile?: string;
    patterns?: string;
    quick?: string;
    json?: string;
    profile?: string;
    patterns?: string;
    analyze?: string;
    analyze?: string;
    quick?: string;
    analyze?: string;
    profile?: string;
    analyze?: string;
    patterns?: string;
  };
}

/**
 * /perf-rag
 * Measure RAG query latency and enforce a simple performance threshold.
 * @category orchestration, knowledge
 * @example
 * - `python D:\scripts\perf_check_rag.py --query "$QUERY" --runs 3 --max-ms-per-query 1500`
 * Behavior:
 */
export interface PerfRagCommand {
  command: '/perf-rag';
  parameters?: {
    rag?: string;
    query?: string;
    runs?: string;
    max-ms-per-query?: string;
  };
}

/**
 * /production-dashboard
 * Show a consolidated production dashboard for the Claude + Codex system.
 * @category evolution, operations
 * @requires /runtime
 * @example
 * - `python D:\claude\tools\command_usage_logger.py --command /production-dashboard`
 * - `python D:\claude\tools\production_dashboard.py`
 */
export interface ProductionDashboardCommand {
  command: '/production-dashboard';
  parameters?: {
    dashboard?: string;
    command?: string;
    dashboard?: string;
    readable?: string;
    output-format?: string;
  };
}

/**
 * /project-index
 * Build a high-level index of all top-level projects under `D:\` and write it to `D:\MASTER_INDEX\project_index.json`.
 * @category knowledge
 * @example
 * - `python D:\claude\tools\project_indexer.py --write-index --output-format text`
 * Output:
 */
export interface ProjectIndexCommand {
  command: '/project-index';
  parameters?: {
    index?: string;
    level?: string;
    level?: string;
    write-index?: string;
    output-format?: string;
  };
}

/**
 * /project-overlaps
 * Scan all top-level projects under `D:\` and detect overlapping or similar utilities across projects.
 * @category orchestration, operations
 * @example
 * - `python D:\claude\tools\project_overlap_scan.py --output-format text`
 * Output:
 */
export interface ProjectOverlapsCommand {
  command: '/project-overlaps';
  parameters?: {
    overlaps?: string;
    level?: string;
    output-format?: string;
  };
}

/**
 * /queue-tasks
 * @category testing, security, orchestration, operations
 * @example
 * **
 * ```bash
 */
export interface QueueTasksCommand {
  command: '/queue-tasks';
  parameters?: {
    -?: string;
    tasks?: string;
    launch?: string;
    -?: string;
    healing?: string;
    chain?: string;
    queue?: string;
    launch?: string;
    start?: string;
    auto_chain_resumer?: string;
  };
}

/**
 * /rag-build-index
 * Build a TF-IDF + LSA index over the prepared RAG documents for fast semantic search.
 * @category knowledge
 * @example
 * - `python D:\claude\tools\rag_build_index.py`
 * Output:
 */
export interface RagBuildIndexCommand {
  command: '/rag-build-index';
  parameters?: {
    build-index?: string;
    IDF?: string;
  };
}

/**
 * /rag-prepare
 * Build a RAG corpus from research documents under `.claude` and `MASTER_INDEX`.
 * @category knowledge
 * @example
 * - `python D:\claude\tools\rag_prepare_documents.py`
 * Output:
 */
export interface RagPrepareCommand {
  command: '/rag-prepare';
  parameters?: {
    prepare?: string;
  };
}

/**
 * /rag-query
 * Query the local RAG index built from your research documents.
 * @category knowledge
 * @example
 * - `python D:\claude\tools\rag_query.py --query "$QUERY" --top-k 5`
 * Output:
 */
export interface RagQueryCommand {
  command: '/rag-query';
  parameters?: {
    query?: string;
    query?: string;
    top-k?: string;
    k?: string;
  };
}

/**
 * /record-movements
 * @category orchestration, operations
 * @requires /failure, /site
 * @example
 * Start the Recursive Movement Engine to capture your actions.
 */
export interface RecordMovementsCommand {
  command: '/record-movements';
  parameters?: {
    movements?: string;
    aggressive?: string;
  };
}

/**
 * /recursive-prompt
 * @category evolution, knowledge, cognition
 * @example
 * ```
 * /recursive-prompt <query> [--depth N] [--mode MODE]
 * ```
 */
export interface RecursivePromptCommand {
  command: '/recursive-prompt';
  parameters?: {
    recursive?: string;
    prompt?: string;
    depth?: string;
    mode?: string;
    depth?: string;
    mode?: string;
    patterns?: string;
    prompt?: string;
    prompt?: string;
    depth?: string;
    prompt?: string;
    patterns?: string;
    generate?: string;
  };
}

/**
 * /remote-exec
 * @category testing
 * @example
 * ```
 * /remote-exec <command>
 * ```
 */
export interface RemoteExecCommand {
  command: '/remote-exec';
  parameters?: {
    exec?: string;
    exec?: string;
    exec?: string;
    a?: string;
    exec?: string;
    release?: string;
    exec?: string;
    exec?: string;
    installed?: string;
  };
}

/**
 * /reverse-reason
 * @category cognition
 * @example
 * ```
 * /reverse-reason <conclusion> [--depth N] [--prompt] [--visualize]
 * ```
 */
export interface ReverseReasonCommand {
  command: '/reverse-reason';
  parameters?: {
    reason?: string;
    depth?: string;
    prompt?: string;
    visualize?: string;
    depth?: string;
    prompt?: string;
    visualize?: string;
    perspectives?: string;
    operations?: string;
    -----?: string;
    -----------?: string;
    ----?: string;
    ---------?: string;
    --------?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    -?: string;
    reason?: string;
    prompt?: string;
    reason?: string;
    depth?: string;
    visualize?: string;
    reason?: string;
    perspectives?: string;
    prompt?: string;
  };
}

/**
 * /sbom
 * Generate a simple local SBOM (software bill of materials) for Rust and Python components.
 * @category knowledge
 * @example
 * - `D:\scripts\generate_sbom.ps1`
 * Output:
 */
export interface SbomCommand {
  command: '/sbom';
}

/**
 * /security-review
 * @category testing, security
 * @requires /msgpack, /json, /keys, /decompression
 */
export interface SecurityReviewCommand {
  command: '/security-review';
  parameters?: {
    review?: string;
    /** [ ] No command injection vulnerabilities */
    provided?: string;
  };
}

/**
 * /self-audit
 * @category security
 * @requires /tools, /22, /10
 * @example
 * ```
 * /self-audit [--quick] [--json] [--check TOOL]
 * ```
 */
export interface SelfAuditCommand {
  command: '/self-audit';
  parameters?: {
    Audit?: string;
    person?: string;
    audit?: string;
    quick?: string;
    json?: string;
    check?: string;
    quick?: string;
    json?: string;
    check?: string;
    help?: string;
    10?: string;
    runnable?: string;
    audit?: string;
    audit?: string;
    quick?: string;
    audit?: string;
    check?: string;
  };
}

/**
 * /self-evolve
 * @category evolution, orchestration, operations, templates
 * @requires /automation_core, /claude, /tools, /analyze_custom_files, /evolution_status, /config_diff, /multi_ai_orchestrate, /GPT-5
 * @example
 * Simply type: `/self-evolve`
 * This will run all steps automatically and present a comprehensive evolution report.
 */
export interface SelfEvolveCommand {
  command: '/self-evolve';
  parameters?: {
    /** Complete Evolution Cycle */
    evolve?: string;
    to-end?: string;
    AI?: string;
    -?: string;
    output-json?: string;
    AI?: string;
    5?: string;
    output-json?: string;
    -?: string;
    5?: string;
    evolve?: string;
  };
}

/**
 * /spawn-template
 * @category templates
 */
export interface SpawnTemplateCommand {
  command: '/spawn-template';
}

/**
 * /status
 * @category evolution, operations
 * @requires /evolution-status
 */
export interface StatusCommand {
  command: '/status';
  parameters?: {
    status?: string;
    json?: string;
  };
}

/**
 * /suggest-chain
 * @category evolution, security, orchestration, knowledge, operations, cognition
 * @requires /intent
 * @example
 * ```
 * /suggest-chain <message> [--quick] [--list]
 * ```
 */
export interface SuggestChainCommand {
  command: '/suggest-chain';
  parameters?: {
    Suggest?: string;
    chain?: string;
    quick?: string;
    list?: string;
    quick?: string;
    line?: string;
    list?: string;
    ------?: string;
    -----?: string;
    -----------?: string;
    perspective?: string;
    perspective?: string;
    backed?: string;
    tool?: string;
    chain?: string;
    chain?: string;
    quick?: string;
    chain?: string;
    list?: string;
  };
}

/**
 * /super-chain
 * @category evolution, testing, orchestration, operations, templates, cognition
 * @requires /SIMPLE, /evolution-status, /improved
 */
export interface SuperChainCommand {
  command: '/super-chain';
  parameters?: {
    AI?: string;
    AI?: string;
    AI?: string;
    AI?: string;
    status?: string;
    5?: string;
    5?: string;
    5?: string;
    5?: string;
    up?: string;
  };
}

/**
 * /swarm
 * @category orchestration, templates
 * @example
 * ```
 * /swarm [action] [options]
 * ```
 */
export interface SwarmCommand {
  command: '/swarm';
  parameters?: {
    count?: string;
    cycles?: string;
    count?: string;
    cycles?: string;
  };
}

/**
 * /system13
 * @category security, orchestration, operations
 * @example
 * ```bash
 */
export interface System13Command {
  command: '/system13';
  parameters?: {
    ending?: string;
    picture?: string;
    goal?: string;
    goal?: string;
    priority?: string;
    max-iterations?: string;
    todowrite?: string;
    Ending?: string;
    Picture?: string;
    level?: string;
    Parallel?: string;
    time?: string;
    goal?: string;
    picture?: string;
    /** Learns from execution patterns */
    time?: string;
    iterations?: string;
    todowrite?: string;
    level?: string;
    Critique?: string;
    time?: string;
    goal?: string;
    time?: string;
    priority?: string;
    15?: string;
    max-iterations?: string;
    time?: string;
    chain?: string;
    initializes?: string;
    approved?: string;
  };
}

/**
 * /tag
 * @category security, orchestration, knowledge
 * @requires /tag-query, /tag-export
 * @example
 * ```
 * /tag <file_or_directory> [options]
 * ```
 */
export interface TagCommand {
  command: '/tag';
  parameters?: {
    detects?: string;
    sentinel-nexus?: string;
    recursive?: string;
    intel?: string;
    agent-orchestration?: string;
    ml?: string;
    evolving-systems?: string;
    sentinel?: string;
    ai-orchestration?: string;
    workspace?: string;
    mismatch?: string;
    query?: string;
    query?: string;
    ml?: string;
    query?: string;
    query?: string;
    type?: string;
    intel?: string;
    export?: string;
    format?: string;
    output?: string;
    export?: string;
    format?: string;
    output?: string;
  };
}

/**
 * /tag-export
 * @category security
 * @example
 * ```
 * /tag-export --format <format> --output <file>
 * ```
 */
export interface TagExportCommand {
  command: '/tag-export';
  parameters?: {
    export?: string;
    format?: string;
    output?: string;
    generated?: string;
    export?: string;
    format?: string;
    output?: string;
    export?: string;
    format?: string;
    output?: string;
    export?: string;
    format?: string;
    output?: string;
  };
}

/**
 * /tag-query
 * @category security, knowledge
 * @example
 * ```
 * /tag-query <query_string>
 * ```
 */
export interface TagQueryCommand {
  command: '/tag-query';
  parameters?: {
    query?: string;
    ml?: string;
    query?: string;
    sentinel?: string;
    query?: string;
    query?: string;
    query?: string;
    type?: string;
    ml?: string;
  };
}

/**
 * /thought-ecosystem
 * @category templates, cognition
 * @requires /creator, /destroyer, /synthesizer, /explorer, /guardian, /trickster, /oracle
 * @example
 * ```
 * /thought-ecosystem [action] [options]
 * ```
 */
export interface ThoughtEcosystemCommand {
  command: '/thought-ecosystem';
  parameters?: {
    ecosystem?: string;
    count?: string;
    ecosystem?: string;
    ecosystem?: string;
    ecosystem?: string;
    ecosystem?: string;
    count?: string;
  };
}

/**
 * /thought-sense
 * @category cognition
 * @example
 * ```
 * /thought-sense <thought> [--introspect] [--trace ID] [--notices]
 * ```
 */
export interface ThoughtSenseCommand {
  command: '/thought-sense';
  parameters?: {
    cognitive?: string;
    sense?: string;
    introspect?: string;
    trace?: string;
    notices?: string;
    introspect?: string;
    trace?: string;
    notices?: string;
    visualize?: string;
    -----?: string;
    -------?: string;
    concept?: string;
    -------?: string;
    -------------?: string;
    sense?: string;
    introspect?: string;
    sense?: string;
    notices?: string;
    sense?: string;
    trace?: string;
    introspect?: string;
  };
}

/**
 * /ultra-critic
 * @category testing, security, orchestration, knowledge
 * @requires /automation_core, /claude, /tools, /advanced_systems, /100
 * @example
 * Review a file:
 * ```
 * /ultra-critic D:\path\to\file.py
 */
export interface UltraCriticCommand {
  command: '/ultra-critic';
  parameters?: {
    Harsh?: string;
    -----?: string;
    -------?: string;
    click?: string;
    tab?: string;
    critic?: string;
    critic?: string;
    critic?: string;
    100?: string;
    -?: string;
  };
}

/**
 * /ultramind-x13
 * @category evolution, orchestration, knowledge, cognition
 * @requires /inverse, /symmetry
 * @example
 * ```bash
 */
export interface UltramindX13Command {
  command: '/ultramind-x13';
  parameters?: {
    x13?: string;
    analysis?: string;
    ----?: string;
    -----------?: string;
    worked?: string;
    analysis?: string;
    each?: string;
    list?: string;
    lists?: string;
    mode?: string;
    mode?: string;
    mode?: string;
    worked?: string;
    outcome?: string;
    mode?: string;
    each?: string;
    items?: string;
    mode?: string;
    items?: string;
    mode?: string;
    X13?: string;
    -?: string;
    -----------?: string;
    -----?: string;
    Unthink?: string;
    ----?: string;
    ---------?: string;
    built?: string;
    /** Confidence: Certain / Probable / Possible / Unlikely */
    to-have?: string;
    add-perspective?: string;
    list-perspectives?: string;
    status?: string;
    x13?: string;
    mode?: string;
    x13?: string;
    mode?: string;
    x13?: string;
    mode?: string;
    x13?: string;
    mode?: string;
    worked?: string;
    outcome?: string;
    x13?: string;
    mode?: string;
  };
}

/**
 * /ultrathink-execute
 * @category evolution, cognition
 * @requires /phase
 * @example
 * ```
 * /ultrathink-execute [--dry-run] [--phase N] [--max-tasks N]
 * ```
 */
export interface UltrathinkExecuteCommand {
  command: '/ultrathink-execute';
  parameters?: {
    execute?: string;
    dry-run?: string;
    phase?: string;
    max-tasks?: string;
    dry-run?: string;
    phase?: string;
    max-tasks?: string;
    Evolve?: string;
    executor?: string;
    executor?: string;
    dry-run?: string;
  };
}

/**
 * /unified-multi-ai
 * Intelligently orchestrate multiple AIs using the best available method
 * @category evolution, orchestration, templates
 * @requires /GPT-5
 * @example
 * ```bash
 */
export interface UnifiedMultiAiCommand {
  command: '/unified-multi-ai';
  parameters?: {
    multi-ai?: string;
    integrated?: string;
    /** Provides setup guidance */
    paste?: string;
    detect?: string;
    check?: string;
    setup?: string;
    mode?: string;
    mode?: string;
    cycles?: string;
    /** GPT-4/GPT-5.1 responds automatically */
    AI?: string;
    paste?: string;
  };
}

/**
 * /workflow
 * @category evolution, orchestration, operations
 * @example
 * ```bash
 */
export interface WorkflowCommand {
  command: '/workflow';
  parameters?: {
    step?: string;
    chained?: string;
    workflow?: string;
    check?: string;
    workflow?: string;
    heal?: string;
    workflow?: string;
    evolution?: string;
    workflow?: string;
    maintenance?: string;
    --------?: string;
    -----------?: string;
    check?: string;
    heal?: string;
    evolution?: string;
    evolution?: string;
    maintenance?: string;
    json?: string;
    quiet?: string;
  };
}

/** Command executor function signature */
export interface CommandExecutor {
  (command: CommandName, parameters?: Record<string, any>): Promise<CommandResult>;
}

/** Command registry mapping */
export interface CommandRegistry {
  '/CHAIN-ALL-COMMANDS': CommandMetadata;
  '/abyssal': CommandMetadata;
  '/adversarial': CommandMetadata;
  '/agent-arena': CommandMetadata;
  '/agent-profiles': CommandMetadata;
  '/analyze-custom-files': CommandMetadata;
  '/attach-security': CommandMetadata;
  '/auto-chain': CommandMetadata;
  '/auto-design': CommandMetadata;
  '/auto-evolve': CommandMetadata;
  '/auto-pipeline': CommandMetadata;
  '/auto-recursive-chain-ai': CommandMetadata;
  '/autorun-all': CommandMetadata;
  '/chaos-evolve': CommandMetadata;
  '/check-drift': CommandMetadata;
  '/config-diff': CommandMetadata;
  '/consciousness-report': CommandMetadata;
  '/contract-adapt': CommandMetadata;
  '/custom-ai': CommandMetadata;
  '/custom-ai-setup': CommandMetadata;
  '/deep-research': CommandMetadata;
  '/deploy-full': CommandMetadata;
  '/destiny': CommandMetadata;
  '/e2e-playwright': CommandMetadata;
  '/e2e-smoke': CommandMetadata;
  '/evolution-status': CommandMetadata;
  '/evolution-summary': CommandMetadata;
  '/experiments-plan': CommandMetadata;
  '/feeling': CommandMetadata;
  '/fix-encoding-errors': CommandMetadata;
  '/fusion': CommandMetadata;
  '/generation': CommandMetadata;
  '/health-probe': CommandMetadata;
  '/hive': CommandMetadata;
  '/hypersense': CommandMetadata;
  '/innovation-scan': CommandMetadata;
  '/intent-map': CommandMetadata;
  '/junk-scan': CommandMetadata;
  '/mega-auto': CommandMetadata;
  '/meshive': CommandMetadata;
  '/multi-ai-orchestrate': CommandMetadata;
  '/multi-websearch': CommandMetadata;
  '/neural-pin': CommandMetadata;
  '/nexus-think': CommandMetadata;
  '/omega': CommandMetadata;
  '/omni-status': CommandMetadata;
  '/pattern-analyze': CommandMetadata;
  '/perf-rag': CommandMetadata;
  '/production-dashboard': CommandMetadata;
  '/project-index': CommandMetadata;
  '/project-overlaps': CommandMetadata;
  '/queue-tasks': CommandMetadata;
  '/rag-build-index': CommandMetadata;
  '/rag-prepare': CommandMetadata;
  '/rag-query': CommandMetadata;
  '/record-movements': CommandMetadata;
  '/recursive-prompt': CommandMetadata;
  '/remote-exec': CommandMetadata;
  '/reverse-reason': CommandMetadata;
  '/sbom': CommandMetadata;
  '/security-review': CommandMetadata;
  '/self-audit': CommandMetadata;
  '/self-evolve': CommandMetadata;
  '/spawn-template': CommandMetadata;
  '/status': CommandMetadata;
  '/suggest-chain': CommandMetadata;
  '/super-chain': CommandMetadata;
  '/swarm': CommandMetadata;
  '/system13': CommandMetadata;
  '/tag': CommandMetadata;
  '/tag-export': CommandMetadata;
  '/tag-query': CommandMetadata;
  '/thought-ecosystem': CommandMetadata;
  '/thought-sense': CommandMetadata;
  '/ultra-critic': CommandMetadata;
  '/ultramind-x13': CommandMetadata;
  '/ultrathink-execute': CommandMetadata;
  '/unified-multi-ai': CommandMetadata;
  '/workflow': CommandMetadata;
}

/** Command statistics */
export interface CommandStats {
  totalCommands: 79;
  totalCategories: 9;
  commandsWithDependencies: 12;
  commandsWithParameters: 77;
}
